# Generated by Django 3.0.4 on 2020-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
